# Site Information
title: adrianf.io
subtitle: Technical Specialist · New Grad
name: Adrian Flores
email: adrianf13.mail@gmail.com
description: >-
  This is a website dedicated to myself, my projects, and my resume. This showcases some of the things I have worked on 
  and built to help further my skills as a software engineer. I love working with technology and building. Programming 
  ignites my creativitiy, and allows to me to expand my knowledge in the field of computer science and development. 

# Site URLs
baseurl: ""
url: "https://adrianf.io"
github_username: adrian1131

# Build Settings
theme: jekyll-theme-console
style: dark 
# other options: light, dark, hacker, nord
listen_for_clients_preferred_style: true
markdown: kramdown
plugins:
  - jekyll-seo-tag

# Include in processing
include:
  - _pages

# Author Information
author:
  name: Adrian Flores
  avatar: "/assets/adrian.png"
  bio: "CS Major @ SCSU · New Grad · Aspiring Software Engineer"
  location: "New Haven, CT"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Adrian1131"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/adrianfdev/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:adrianf13.mail@gmail.com"